
language: python
python:
  - "3.6"
  - "3.7"
# command to install dependencies
install:
  - pip install tox pytest pytest-qt
#  - pip install -r requirements.txt
# command to run tests
env:
  - QT_QPA_PLATFORM=offscreen
script:
#  - python -m pytest
  - tox -e py