on: [push, pull_request]
name: Multi-platform Compatibility Test
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.6', '3.7', '3.8' ,'3.9']
      fail-fast: false
    name: Python ${{ matrix.python-version }} ${{ matrix.os }} build
    env:
      QT_QPA_PLATFORM: offscreen
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - run: pip install tox; tox -e py
