on: [push]
name: Main Workflow
jobs:
  sonarCloudTrigger:
    name: SonarCloud Trigger
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        git fetch --prune --unshallow
    - name: Setup python
      uses: actions/setup-python@v1
      with:
          python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
    - name: Pytest
      run: |
        pip install pytest pytest-cov
        python --version
        pytest --junitxml xunit-reports/xunit-result-python.xml --cov=grabbags --cov-report=xml:coverage-reports/pythoncoverage-pytest.xml
        cat xunit-reports/xunit-result-python.xml
    - name: Pylint
      run: |
        pip install pylint
        mkdir -p reports
        pylint grabbags -r n --msg-template="{path}:{line}: [{msg_id}({symbol}), {obj}] {msg}" --exit-zero > reports/pylint.log
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
